### ISSUE TITLE
Fabio Connecting error to local consul-agent (client)

### ISSUE THREAD

**Issue by TargetFocussed** [eBay/fabio#232] opened 2017-02-06 02:16 UTC
```
ubuntu-vm3@ubuntu-vm3:~$ sudo docker logs 981ac34ba256
2017/02/06 02:12:10 [INFO] Runtime config
{
    "Proxy": {
        "Strategy": "rnd",
        "Matcher": "prefix",
        "NoRouteStatus": 404,
        "MaxConn": 10000,
        "ShutdownWait": 0,
        "DialTimeout": 30000000000,
        "ResponseHeaderTimeout": 0,
        "KeepAliveTimeout": 0,
        "FlushInterval": 1000000000,
        "LocalIP": "172.17.0.4",
        "ClientIPHeader": "",
        "TLSHeader": "",
        "TLSHeaderValue": "",
        "GZIPContentTypes": null
    },
    "Registry": {
        "Backend": "consul",
        "Static": {
            "Routes": ""
        },
        "File": {
            "Path": ""
        },
        "Consul": {
            "Addr": "localhost:8500",
            "Scheme": "http",
            "Token": "",
            "KVPath": "/fabio/config",
            "TagPrefix": "urlprefix-",
            "Register": true,
            "ServiceAddr": ":9998",
            "ServiceName": "fabio",
            "ServiceTags": null,
            "ServiceStatus": [
                "passing"
            ],
            "CheckInterval": 1000000000,
            "CheckTimeout": 3000000000
        }
    },
    "Listen": [
        {
            "Addr": ":9999",
            "Proto": "http",
            "ReadTimeout": 0,
            "WriteTimeout": 0,
            "CertSource": {
                "Name": "",
                "Type": "",
                "CertPath": "",
                "KeyPath": "",
                "ClientCAPath": "",
                "CAUpgradeCN": "",
                "Refresh": 0,
                "Header": null
            },
            "StrictMatch": false
        }
    ],
    "Metrics": {
        "Target": "",
        "Prefix": "{{clean .Hostname}}.{{clean .Exec}}",
        "Names": "{{clean .Service}}.{{clean .Host}}.{{clean .Path}}.{{clean .TargetURL.Host}}",
        "Interval": 30000000000,
        "GraphiteAddr": "",
        "StatsDAddr": "",
        "Circonus": {
            "APIKey": "",
            "APIApp": "fabio",
            "APIURL": "",
            "CheckID": "",
            "BrokerID": ""
        }
    },
    "UI": {
        "Addr": ":9998",
        "Color": "light-green",
        "Title": ""
    },
    "Runtime": {
        "GOGC": 800,
        "GOMAXPROCS": 4
    }
}
2017/02/06 02:12:10 [INFO] Version 1.3.7 starting
2017/02/06 02:12:10 [INFO] Go runtime is go1.7.4
2017/02/06 02:12:10 [INFO] Metrics disabled
2017/02/06 02:12:10 [INFO] Setting GOGC=800
2017/02/06 02:12:10 [INFO] Setting GOMAXPROCS=4
2017/02/06 02:12:10 [FATAL] Error initializing backend. Get http://localhost:8500/v1/agent/self: dial tcp 127.0.0.1:8500: getsockopt: connection refused
ubuntu-vm3@ubuntu-vm3:~$ curl http://localhost:8500/v1/agent/self
{"Config":{"DevMode":false,"Performance":{"RaftMultiplier":0},"Bootstrap":false,"BootstrapExpect":0,"Server":false,"Datacenter":"dc1","DataDir":"/consul/data",                                      "DNSRecursor":"","DNSRecursors":["8.8.8.8"],"DNSConfig":{"NodeTTL":0,"ServiceTTL":null,"AllowStale":true,"EnableTruncate":false,"UDPAnswerLimit":3,"MaxStale":3                                      15360000000000000,"OnlyPassing":false,"DisableCompression":false,"RecursorTimeout":2000000000},"Domain":"consul.","LogLevel":"INFO","NodeName":"agent1","Client                                      Addr":"0.0.0.0","BindAddr":"0.0.0.0","SerfWanBindAddr":"","SerfLanBindAddr":"","AdvertiseAddr":"10.193.16.117","AdvertiseAddrs":{"SerfLan":null,"SerfLanRaw":""                                      ,"SerfWan":null,"SerfWanRaw":"","RPC":null,"RPCRaw":""},"AdvertiseAddrWan":"10.193.16.117","TranslateWanAddrs":false,"Ports":{"DNS":53,"HTTP":8500,"HTTPS":-1,"                                      RPC":8400,"SerfLan":8301,"SerfWan":8302,"Server":8300},"Addresses":{"DNS":"","HTTP":"","HTTPS":"","RPC":""},"TaggedAddresses":{"lan":"10.193.16.117","wan":"10.                                      193.16.117"},"LeaveOnTerm":true,"SkipLeaveOnInt":false,"Telemetry":{"StatsiteAddr":"","StatsdAddr":"","StatsitePrefix":"consul","DisableHostname":false,"DogSta                                      tsdAddr":"","DogStatsdTags":null,"CirconusAPIApp":"","CirconusAPIURL":"","CirconusSubmissionInterval":"","CirconusCheckSubmissionURL":"","CirconusCheckID":"","                                      CirconusCheckForceMetricActivation":"","CirconusCheckInstanceID":"","CirconusCheckSearchTag":"","CirconusCheckTags":"","CirconusCheckDisplayName":"","CirconusB                                      rokerID":"","CirconusBrokerSelectTag":""},"Protocol":2,"EnableDebug":false,"VerifyIncoming":false,"VerifyOutgoing":false,"VerifyServerHostname":false,"CAFile":                                      "","CertFile":"","KeyFile":"","ServerName":"","StartJoin":["10.193.6.129"],"StartJoinWan":[],"RetryJoin":[],"RetryMaxAttempts":0,"RetryIntervalRaw":"","RetryJo                                      inEC2":{"Region":"","TagKey":"","TagValue":"","AccessKeyID":"","SecretAccessKey":""},"RetryJoinWan":[],"RetryMaxAttemptsWan":0,"RetryIntervalWanRaw":"","Reconn                                      ectTimeoutLan":0,"ReconnectTimeoutLanRaw":"","ReconnectTimeoutWan":0,"ReconnectTimeoutWanRaw":"","EnableUi":false,"UiDir":"/consul/ui","PidFile":"","EnableSysl                                      og":false,"SyslogFacility":"LOCAL0","RejoinAfterLeave":false,"CheckUpdateInterval":300000000000,"CheckReapInterval":30000000000,"CheckDeregisterIntervalMin":60                                      000000000,"ACLDatacenter":"","ACLTTL":30000000000,"ACLTTLRaw":"","ACLDefaultPolicy":"allow","ACLDisabledTTL":120000000000,"ACLDownPolicy":"extend-cache","ACLEn                                      forceVersion8":false,"Watches":null,"DisableRemoteExec":false,"DisableUpdateCheck":true,"DisableAnonymousSignature":false,"HTTPAPIResponseHeaders":null,"AtlasI                                      nfrastructure":"","AtlasJoin":false,"AtlasEndpoint":"","DisableCoordinates":false,"Revision":"'a9afa0c'","Version":"0.7.2","VersionPrerelease":"","UnixSockets"                                      :{"Usr":"","Grp":"","Perms":""},"SessionTTLMin":0,"SessionTTLMinRaw":""},"Coord":{"Vec":[0.032217879347328664,-0.0030687217935303937,0.02985289938769857,-0.063                                      00606974413012,-0.007623374715464906,-0.021246270207282075,0.08837407114865138,-0.07573375524172828],"Error":0.04591570727285668,"Adjustment":-0.00015269277513                                      334565,"Height":0.0002227387693412941},"Member":{"Name":"agent1","Addr":"10.193.16.117","Port":8301,"Tags":{"build":"0.7.2:'a9afa0c","dc":"dc1","role":"node","                                      vsn":"2","vsn_max":"3","vsn_min":"2"},"Status":1,"ProtocolMin":1,"ProtocolMax":5,"ProtocolCur":2,"DelegateMin":2,"DelegateMax":4,"DelegateCur":4},"Stats":{"age                                      nt":{"check_monitors":"0","check_ttls":"0","checks":"0","services":"8"},"build":{"prerelease":"","revision":"'a9afa0c","version":"0.7.2"},"consul":{"known_serv                                      ers":"1","server":"false"},"runtime":{"arch":"amd64","cpu_count":"4","goroutines":"34","max_procs":"4","os":"linux","version":"go1.7.3"},"serf_lan":{"encrypted                                      ":"false","event_queue":"0","event_time":"2","failed":"0","health_score":"0","intent_queue":"0","left":"0","member_time":"2","members":"2","query_queue":"0","q                                      uery_time":"1"}}}ubuntu-vm3@ubuntu-vm3:~$ sudo docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS               NAMES
e19de9ab8e32        gliderlabs/connectable:latest   "/bin/connectable"       25 hours ago        Up 25 hours                             connectable
9106a30176e4        mgood/resolvable                "/bin/resolvable"        27 hours ago        Up 27 hours                             pedantic_lamarr
2905abbbd7e7        gliderlabs/registrator:latest   "/bin/registrator ..."   4 days ago          Up 4 days                               registrator
2d06538c340f        wdijkerman/consul               "/sbin/tini -- /bi..."   4 days ago          Up 4 days                               consul-client
ubuntu-vm3@ubuntu-vm3:~$
```

**Comment by magiconair** [comment] 2017-02-06 09:11
This looks like a duplicate of #223. Please have a look at the comment from @raben2 which describes how to use docker-compose for this.

**Closed** 2017-02-06 09:13 UTC
