### ISSUE TITLE
Q: HTTPS end-to-end

### ISSUE THREAD

**Issue by sichou** [eBay/fabio#185] opened 2016-11-15 01:39 UTC
I want to config fabio for [ https -> fabio:9999 -> https -> backend ]

1. I'm able to config fabio to listen on https:9999
2. My backend services only listen on https:4321

How can I config fabio to add route to https enabled backend that are dynamically registered to Consul?

When making a https request to fabio listening on 9999, fabio complaints about "http: proxy error: malformed HTTP response "\x15\x03\x00\x02\x02".  At the same time, my backend complaints about "http: TLS handshake error from 127.0.0.1:46998: tls: first record does not look like a TLS handshake"  It appears that fabio attempts to route the request to my backend using HTTP, not HTTPS, where HTTPS is expected.

Is this issue similar to #181 and #111?

SC

**Comment by magiconair** [comment] 2016-11-16 00:18
Https backends are only supported via the tcp+sni proxy for now

**Comment by magiconair** [comment] 2016-12-14 13:05
Closing as duplicate of #181

**Closed by magiconair** 2016-12-14 13:05 UTC
Labels: question
