### ISSUE TITLE
Routing by path

### ISSUE THREAD

**Issue by Salmondx** [eBay/fabio#164] opened 2016-09-22 13:13 UTC
Hi,
I have a question and didn't found a solution in docs.
Is it possible in fabio to pass to service only path variables after urlprefix?
E.g. I've got a service `test-service` with `urlpreifx-/test-service`.
And now i want to send http request like this:
`http localhost:9999/test-service/test/api`
I only want to pass `/test/api` part, not the whole path, and fabio does the second.

In nginx i can add `/` after a location path and all path variables will be propagated except one that used for routing.

**Comment by magiconair** [comment] 2016-09-22 13:26
Fabio does not support path stripping right now. There is a ticket open for this where you can read the reasoning. I'm probably going to add this in the future but I'm going to focus on other things first.

**Comment by magiconair** [comment] 2016-12-21 15:20
I'm closing this as a duplicate of #44. Change for path stripping is in progress. See branch.

**Closed by magiconair** 2016-12-21 15:20 UTC
Labels: enhancement
