### ISSUE TITLE
Q: Why does Fabio log the entire route table on every change?

### ISSUE THREAD

**Issue by stevehorsfield** [eBay/fabio#227] opened 2017-02-03 14:39 UTC
### Context

Based on: https://github.com/eBay/fabio/blob/128b59ccb543832312ea2050b8154b4fd0ee93b8/route/table.go#L45-L54

We see thousands of messages like:

```
2017/02/03 14:18:19 [INFO] Updated config to
```

and

```
route add my-service my-service/ http://a.b.c.d:port/ tags "private,private:my-service.service.consul/,private:my-service/"
```

### Expected behaviour

We expect to only see logs of changes (the delta), not the entire route table.

### Perceived behaviour

I think that Fabio is logging the entire route table every time a change occurs.

### Comment

Could you please confirm if this is expected behaviour? If so, should there be an option to disable the output of these messages? If not, can we get it fixed? We're happy to put a PR together.

A delta would certainly be a desirable output.

**Comment by magiconair** [comment] 2017-02-03 14:55
At this point this is the expected behavior. I agree that only (or additionally) logging the delta may be beneficial for debugging purposes and I may do that in the future. As stated in #226 the reason you are seeing thousands of messages of the routing table is because something in your environment is not stable. That is the only information you can derive from that. Once you find and fix that problem then you will only see the updated routing table. I'll add the delta thing to the list of things to add. This would indeed be useful.

**Comment by stevehorsfield** [comment] 2017-02-03 14:57
We have a lot of services, some of which do flap (particularly in pre-prod). However, I'm pretty sure our logging isn't due to flapping per se (it may be due to the way Consul is handling health check changes). In any case, if we can't get this output reduced through some mechanism we'll have to fork. Another option is to control the logging detail through feature flags. Is that something you are open to?

**Comment by magiconair** [comment] 2017-02-03 15:01
If this is a production issue which you can't fix easily them I'm open to bump the priority on this. Usually, I push back on adding features which mask a different problem. For now just comment out the log lines and build it yourself. I'll see what I can do.

**Comment by magiconair** [comment] 2017-02-03 15:14
The other thing we're doing in QA environments is to run fabio via upstart and rotate the log files once they've reached a certain size.

**Comment by stevehorsfield** [comment] 2017-02-03 15:26
We're shipping our logs directly to a SaaS log vendor, so rotation isn't needed for us. I'm looking at Consul to see if I can find the logic that might link to this behaviour. Appreciate your feedback.

**Comment by magiconair** [comment] 2017-02-18 22:12
I think we can close this one. Please comment if there is something to add and I'll re-open if necessary.

**Closed by magiconair** 2017-02-18 22:12 UTC
Labels: question
