### ISSUE TITLE
fabio route not removed after consul deregister

### ISSUE THREAD

**Issue by strarsis** [eBay/fabio#22] opened 2015-12-07 17:44 UTC
When running the demo server, it registers itself in consul, being listed by consul as healthy.
````
$ curl http://localhost:8500/v1/catalog/services

{"consul":[],"consul-server-8500":[],"fabio":[],"fabio-9998":[],"fabio-9999":[],"svc-a":["urlprefix-domain.com/foo"]}

$ curl http://localhost:8500/v1/catalog/service/svc-a

[{"Node":"74bd1b630c8d","Address":"172.17.0.2","ServiceID":"svc-a-172.17.0.1:5000","ServiceName":"svc-a","ServiceTags":["urlprefix-domain.com/foo"],"ServiceAddress":"172.17.0.1","ServicePort":5000}]
````

Fabio also correctly adds the route to routing table, also listed in fabio web gui.
````
1	svc-a	domain.com	/foo	http://172.17.0.1:5000/	100%
````

When the demo server is shut down (Ctrl+c), it reports that it deregistered itself in consul:
````
2015/12/07 18:35:16 Deregistered service "svc-a" in consul
````
And indeed, consul doesn't list the demo server anymore:
````
$ curl http://localhost:8500/v1/catalog/services

{"consul":[],"consul-server-8500":[],"fabio":[],"fabio-9998":[],"fabio-9999":[]}

$ curl http://localhost:8500/v1/catalog/service/svc-a

[]
````

However, in fabio web gui, the route is still listed:
````
1	svc-a	domain.com	/foo	http://172.17.0.1:5000/	100%
````

Thank you and
with best regards

**Comment by magiconair** [comment] 2015-12-07 19:14
Can you please post the fabio log? It should note the change in the health and service status and print the generated routing table.

**Comment by magiconair** [comment] 2015-12-07 19:16
Also, since you're using docker could you describe how you are running the individual applications right now? What is running where and can they all talk to each other on the addresses and ports you've configured ...

**Comment by strarsis** [comment] 2015-12-07 20:01
https://github.com/strarsis/consul-fabio-example/

With best regards

**Comment by magiconair** [comment] 2015-12-07 20:25
@strarsis The logs are more helpful at this point

**Comment by strarsis** [comment] 2015-12-07 21:28
Log file attached:
[log.txt](https://github.com/eBay/fabio/files/54591/log.txt)

**Comment by magiconair** [comment] 2015-12-07 22:19
I think the confusion comes from the registrator. You don't need the registrator for registering either fabio or the demo service. They are both capable of registering themself. Try removing the registrator from your setup and just run the binaries. That should work.

**Comment by strarsis** [comment] 2015-12-07 22:23
Thank you your answer.
I removed the registrator service, but the route still persists in fabio routing table:
https://github.com/strarsis/consul-fabio-example/blob/master/docker-compose.yml
I updated the example repo so it can be directly tested.

**Comment by magiconair** [comment] 2015-12-11 16:03
I think this a duplicate of issue #23. fabio does not flush the last route. I'll release a 1.0.7 to fix this properly.

**Closed** 2015-12-13 19:59 UTC
Labels: bug

**Comment by strarsis** [comment] 2015-12-13 20:18
I updated the docker-compose and can confirm that it works now.
