### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by DanielCharczynski** [eBay/fabio#241] opened 2017-02-13 12:58 UTC
Hello

at the moment as far as I know fabio doesn't support calls https as a client - but it is our requirement 
Is there any possibility to call service endpoint via https?

we use **proto-https** consul tag to get to know if it is http or http

Can I get contact to you Frank?

Regards
Daniel

**Comment by magiconair** [comment] 2017-02-13 13:36
Sure. You can find me on LinkedIn. 

Frank Schröder

**Comment by magiconair** [comment] 2017-02-13 16:01
I'll close this as a duplicate of #181

**Closed by magiconair** 2017-02-13 16:01 UTC
